/**
 * Sweep accrued fees from the hatch-launched stacc-on-ketamine token.
 *
 * Run with:
 *   HATCH_MINT=<mintFromLaunch> pnpm tsx scripts/hatch-claim.ts
 *
 * Uses the same launcher keypair generated by hatch-launch.ts.
 */

import { existsSync, readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { Connection, Keypair, PublicKey } from '@solana/web3.js'

const KEYPAIR_PATH =
  process.env.HATCH_LAUNCHER_KEYPAIR ??
  `${homedir()}/.config/stacsol/hatch-launcher.json`

const RPC_URL = process.env.RPC_URL
const MINT = process.env.HATCH_MINT
if (!RPC_URL || !MINT) {
  console.error('set RPC_URL and HATCH_MINT env vars')
  process.exit(1)
}

async function main() {
  if (!existsSync(KEYPAIR_PATH)) {
    console.error(`launcher keypair not found at ${KEYPAIR_PATH}`)
    process.exit(1)
  }
  const signer = Keypair.fromSecretKey(
    Uint8Array.from(JSON.parse(readFileSync(KEYPAIR_PATH, 'utf-8')) as number[]),
  )
  const connection = new Connection(RPC_URL!, 'confirmed')
  const mint = new PublicKey(MINT!)

  const { HatchClient } = await import('hatch-sdk')
  const hatch = new HatchClient({ connection, signer })

  const status = await hatch.getLaunchStatus({ mint })
  console.log(`positions: ${status.positions.length}`)
  console.log(`total claimable: ${status.totalClaimableSol} SOL`)
  if (status.totalClaimableSol <= 0) {
    console.log('nothing to claim')
    return
  }

  const r = await hatch.claimFees({ mint })
  console.log(`claimed ${r.positionsClaimed} position(s)`)
  for (const sig of r.signatures) {
    console.log(`  https://solscan.io/tx/${sig}`)
  }
  if (r.failures?.length) {
    console.log('failures:')
    for (const f of r.failures) console.log(`  ${f.position}: ${f.error}`)
  }
}

main().catch((e) => {
  console.error('claim failed:', e)
  process.exit(1)
})
